# Generated by Django 5.0.1 on 2024-03-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='default_image.jpg', upload_to='product_images'),
        ),
    ]
